name: CI/CD Pipeline

on:
  push:
    branches:
      - main   # Trigger only on merges to the main branch

jobs:
  ci-cd-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Codes
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # Step 3: Login to Amazon ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1


      # Step 4: Build Docker Images
      - name: Build Docker Image
        run: |
          IMAGE_TAG=latest
          docker build -t clo835-assign01:$IMAGE_TAG ./flaskapp

      # Step 5: Tag & Push Docker Image to ECR
      - name: Tag & Push to ECR
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=us-east-1
          REPO_NAME=flaskapp
          IMAGE_TAG=latest

          ECR_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME"
          docker tag clo835-assign01:$IMAGE_TAG $ECR_URI:$IMAGE_TAG
          docker push $ECR_URI:$IMAGE_TAG

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 instance public IP
          username: ec2-user                   # EC2 instance username (could be ubuntu, ec2-user, etc.)
          key: ${{ secrets.MY_SSH }}      # The private SSH key stored in GitHub Secrets
          port: 22,80                             # Port 22 is standard for SSH
          script: |
            # Debug info
            echo "AWS Account ID: $(aws sts get-caller-identity --query Account --output text)"
            echo "ECR URI: $ECR_URI"
      
            ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
            REGION=us-east-1
            REPO_NAME=flaskapp
            IMAGE_TAG=latest
      
            ECR_URI="$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME"
            aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ECR_URI
            docker pull $ECR_URI:$IMAGE_TAG
            docker run -d -p 8080:8080 $ECR_URI:$IMAGE_TAG
